/*Este es el layout principal de la aplicación. Todo lo que se ponga aquí, se mostrará en todas las páginas.*/
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "McQueen Tires",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col font-sans">
        <main className="pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
