/*Este es el layout principal de la aplicación. Todo lo que se ponga aquí, se mostrará en todas las páginas.*/
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "McQueen Tires",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">
        {/*<Navbar />*/}
        <main className="pt-16">
          {children}
          <Toaster position="top-right" closeButton={false} />
        </main>
      </body>
    </html>
  );
}
