// <auto-generated />
using System;
using DatabaseHastaCompraVenta.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations.DblosAmigos
{
    [DbContext(typeof(DblosAmigosContext))]
    partial class DblosAmigosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Ciudad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCiudad"));

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCiudad");

                    b.HasIndex("IdPais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CI");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Persona");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("RUC");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPersona");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Deposito", b =>
                {
                    b.Property<int>("IdDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Deposito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeposito"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDeposito");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Direccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Calle1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Calle_1");

                    b.Property<string>("Calle2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Calle_2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Ciudad");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CI");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Ingreso");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Persona");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RUC");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdPersona");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasCompra", b =>
                {
                    b.Property<int>("IdFacturaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFacturaCompra"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdOrdenCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Compra");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Proveedor");

                    b.Property<string>("NroComprobante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nro_Comprobante");

                    b.Property<string>("Timbrado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdFacturaCompra");

                    b.HasIndex("IdOrdenCompra");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Facturas_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasComprasDetalle", b =>
                {
                    b.Property<int>("IdFacturaCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFacturaCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdFacturaCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Bruto");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_IVA");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Neto");

                    b.HasKey("IdFacturaCompraDetalle");

                    b.HasIndex("IdFacturaCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("Facturas_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasVenta", b =>
                {
                    b.Property<int>("IdFacturaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFacturaVenta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Fecha_Pago");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("IdMedioPagoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Medio_Pago_Compra");

                    b.Property<int>("IdOrdenVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Venta");

                    b.Property<int>("IdTimbrado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Timbrado");

                    b.Property<string>("NroComprobante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nro_Comprobante");

                    b.HasKey("IdFacturaVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMedioPagoCompra");

                    b.HasIndex("IdOrdenVenta");

                    b.HasIndex("IdTimbrado");

                    b.ToTable("Facturas_Ventas", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasVentasDetalle", b =>
                {
                    b.Property<int>("IdFacturaVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Venta_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFacturaVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdFacturaVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Venta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Bruto");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_IVA");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Total_Neto");

                    b.HasKey("IdFacturaVentaDetalle");

                    b.HasIndex("IdFacturaVenta");

                    b.HasIndex("IdProducto");

                    b.ToTable("Facturas_Ventas_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.MediosPagosCompra", b =>
                {
                    b.Property<int>("IdMedioPagoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Medio_Pago_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedioPagoCompra"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMedioPagoCompra");

                    b.ToTable("Medios_Pagos_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosCompra", b =>
                {
                    b.Property<int>("IdNotaCreditoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaCreditoCompra"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdFacturaCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra");

                    b.Property<int>("IdNotaDevolucionCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Compra");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Timbrado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 0)");

                    b.HasKey("IdNotaCreditoCompra");

                    b.HasIndex("IdFacturaCompra");

                    b.HasIndex("IdNotaDevolucionCompra");

                    b.ToTable("Notas_Creditos_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosComprasDetalle", b =>
                {
                    b.Property<int>("IdNotaCreditoCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaCreditoCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdNotaCreditoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNotaCreditoCompraDetalle");

                    b.HasIndex("IdNotaCreditoCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("Notas_Creditos_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosVenta", b =>
                {
                    b.Property<int>("IdNotaCreditoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaCreditoVenta"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Fecha_Emision");

                    b.Property<int>("IdFacturaVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Venta");

                    b.Property<int>("IdNotaDevolucionVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Venta");

                    b.Property<int>("IdTimbrado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Timbrado");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNotaCreditoVenta");

                    b.HasIndex("IdFacturaVenta");

                    b.HasIndex("IdNotaDevolucionVenta");

                    b.HasIndex("IdTimbrado");

                    b.ToTable("Notas_Creditos_Ventas", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosVentasDetalle", b =>
                {
                    b.Property<int>("IdNotaCreditoVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Venta_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaCreditoVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdNotaCreditoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Credito_Venta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNotaCreditoVentaDetalle");

                    b.HasIndex("IdNotaCreditoVenta");

                    b.HasIndex("IdProducto");

                    b.ToTable("Notas_Creditos_Ventas_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesCompra", b =>
                {
                    b.Property<int>("IdNotaDevolucionCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaDevolucionCompra"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdFacturaCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdNotaDevolucionCompra")
                        .HasName("PK_Notas_Devoluciones_Compra");

                    b.HasIndex("IdFacturaCompra");

                    b.ToTable("Notas_Devoluciones_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesComprasDetalle", b =>
                {
                    b.Property<int>("IdNotaDevolucionCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaDevolucionCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdNotaDevolucionCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNotaDevolucionCompraDetalle");

                    b.HasIndex("IdNotaDevolucionCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("Notas_Devoluciones_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesVenta", b =>
                {
                    b.Property<int>("IdNotaDevolucionVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaDevolucionVenta"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdFacturaVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Venta");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdNotaDevolucionVenta")
                        .HasName("PK_Notas_Devoluciones_Venta");

                    b.HasIndex("IdFacturaVenta");

                    b.ToTable("Notas_Devoluciones_Ventas", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesVentasDetalle", b =>
                {
                    b.Property<int>("IdNotaDevolucionVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_Venta_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaDevolucionVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdNotaDevolucionVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Nota_Devolucion_venta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdNotaDevolucionVentaDetalle");

                    b.HasIndex("IdNotaDevolucionVenta");

                    b.HasIndex("IdProducto");

                    b.ToTable("Notas_Devoluciones_Ventas_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesCompra", b =>
                {
                    b.Property<int>("IdOrdenCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenCompra"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.Property<int>("IdPedidoCotizacion")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Cotizacion");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Proveedor");

                    b.HasKey("IdOrdenCompra");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPedidoCotizacion");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Ordenes_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesComprasDetalle", b =>
                {
                    b.Property<int>("IdOrdenCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.HasKey("IdOrdenCompraDetalle");

                    b.HasIndex("IdOrdenCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("Ordenes_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesMediosPagosCompra", b =>
                {
                    b.Property<int>("IdOrdenMedioPagoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Medio_Pago_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenMedioPagoCompra"));

                    b.Property<int>("IdMedioPagoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Medio_Pago_Compra");

                    b.Property<int>("IdOrdenPagoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Pago_Compra");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdOrdenMedioPagoCompra");

                    b.HasIndex("IdMedioPagoCompra");

                    b.HasIndex("IdOrdenPagoCompra");

                    b.ToTable("Ordenes_Medios_Pagos_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesPagosCompra", b =>
                {
                    b.Property<int>("IdOrdenPagoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Pago_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenPagoCompra"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Proveedor");

                    b.HasKey("IdOrdenPagoCompra");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Ordenes_Pagos_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesPagosComprasDetalle", b =>
                {
                    b.Property<int>("IdOrdenPagoCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Pago_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenPagoCompraDetalle"));

                    b.Property<int>("IdFacturaCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Factura_Compra");

                    b.Property<int>("IdOrdenPagoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Pago_Compra");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdOrdenPagoCompraDetalle");

                    b.HasIndex("IdFacturaCompra");

                    b.HasIndex("IdOrdenPagoCompra");

                    b.ToTable("Ordenes_Pagos_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesVenta", b =>
                {
                    b.Property<int>("IdOrdenVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenVenta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Presupuesto");

                    b.HasKey("IdOrdenVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPresupuesto");

                    b.ToTable("Ordenes_Ventas", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesVentasDetalle", b =>
                {
                    b.Property<int>("IdOrdenVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_venta_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Orden_Venta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.HasKey("IdOrdenVentaDetalle");

                    b.HasIndex("IdOrdenVenta");

                    b.HasIndex("IdProducto");

                    b.ToTable("Ordenes_Ventas_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pais");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Pariente", b =>
                {
                    b.Property<int>("IdPariente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pariente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPariente"));

                    b.Property<short>("Edad")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Empleado");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("character(1)")
                        .HasColumnName("Tipo_Relacion")
                        .IsFixedLength();

                    b.HasKey("IdPariente");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Parientes");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCompra", b =>
                {
                    b.Property<int>("IdPedidoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedidoCompra"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("integer")
                        .HasColumnName("Numero_Pedido");

                    b.HasKey("IdPedidoCompra")
                        .HasName("PK_Pedidos_Compra");

                    b.HasIndex("IdEstado");

                    b.ToTable("Pedidos_Compras", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosComprasDetalle", b =>
                {
                    b.Property<int>("IdPedidoCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Compra_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedidoCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdPedidoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.HasKey("IdPedidoCompraDetalle");

                    b.HasIndex("IdPedidoCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("Pedidos_Compras_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCotizaciones", b =>
                {
                    b.Property<int>("IdPedidoCotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Cotizacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedidoCotizacion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.Property<int>("IdPedidoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Compra");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("integer")
                        .HasColumnName("Numero_Pedido");

                    b.HasKey("IdPedidoCotizacion");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPedidoCompra");

                    b.ToTable("Pedidos_Cotizaciones", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCotizacionesDetalle", b =>
                {
                    b.Property<int>("IdPedidoCotizacionDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Cotizacion_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedidoCotizacionDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdPedidoCotizacion")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido_Cotizacion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("PrecioProducto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Producto");

                    b.HasKey("IdPedidoCotizacionDetalle");

                    b.HasIndex("IdPedidoCotizacion");

                    b.HasIndex("IdProducto");

                    b.ToTable("Pedidos_Cotizaciones_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Direccion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdDireccion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Presupuesto", b =>
                {
                    b.Property<int>("IdPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Presupuesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuesto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Fecha_Vencimiento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Estado");

                    b.HasKey("IdPresupuesto");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PresupuestosDetalle", b =>
                {
                    b.Property<int>("IdPresupuestoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Presupuesto_Detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuestoDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Presupuesto");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("IVA");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPresupuestoDetalle");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdProducto");

                    b.ToTable("Presupuestos_Detalles", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EsServicio")
                        .HasColumnType("boolean")
                        .HasColumnName("Es_Servicio");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Categoria");

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Marca");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Porcentaje_IVA");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Precio_Unitario");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Proveedor");

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nombre_Fantasia");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Razon_Social");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RUC");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.StocksDeposito", b =>
                {
                    b.Property<int>("IdDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Deposito");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Producto");

                    b.HasKey("IdDeposito");

                    b.HasIndex("IdProducto");

                    b.ToTable("Stocks_Depositos", (string)null);
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Timbrado", b =>
                {
                    b.Property<int>("IdTimbrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Timbrado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTimbrado"));

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Final");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("RUC");

                    b.HasKey("IdTimbrado");

                    b.ToTable("Timbrados");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Ciudad", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Pais", "IdPaisNavigation")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Ciudades_Paises1");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Cliente", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Personas");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Direccion", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Ciudad", "IdCiudadNavigation")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdCiudad")
                        .IsRequired()
                        .HasConstraintName("FK_Direcciones_Ciudades1");

                    b.Navigation("IdCiudadNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Empleado", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Personas");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesCompra", "IdOrdenCompraNavigation")
                        .WithMany("FacturasCompras")
                        .HasForeignKey("IdOrdenCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Compras_Ordenes_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("FacturasCompras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Compras_Proveedores");

                    b.Navigation("IdOrdenCompraNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasCompra", "IdFacturaCompraNavigation")
                        .WithMany("FacturasComprasDetalles")
                        .HasForeignKey("IdFacturaCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Compras_Detalles_Facturas_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("FacturasComprasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Compras_Detalles_Productos");

                    b.Navigation("IdFacturaCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasVenta", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Cliente", "IdClienteNavigation")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Clientes");

                    b.HasOne("DatabaseHastaCompraVenta.Models.MediosPagosCompra", "IdMedioPagoCompraNavigation")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdMedioPagoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Medios_Pagos_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesVenta", "IdOrdenVentaNavigation")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdOrdenVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Ordenes_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Timbrado", "IdTimbradoNavigation")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdTimbrado")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Timbrados");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdMedioPagoCompraNavigation");

                    b.Navigation("IdOrdenVentaNavigation");

                    b.Navigation("IdTimbradoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasVentasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasVenta", "IdFacturaVentaNavigation")
                        .WithMany("FacturasVentasDetalles")
                        .HasForeignKey("IdFacturaVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Detalles_Facturas_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("FacturasVentasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Ventas_Detalles_Productos");

                    b.Navigation("IdFacturaVentaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasCompra", "IdFacturaCompraNavigation")
                        .WithMany("NotasCreditosCompras")
                        .HasForeignKey("IdFacturaCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Compras_Facturas_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasDevolucionesCompra", "IdNotaDevolucionCompraNavigation")
                        .WithMany("NotasCreditosCompras")
                        .HasForeignKey("IdNotaDevolucionCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Compras_Notas_Devoluciones_Compras");

                    b.Navigation("IdFacturaCompraNavigation");

                    b.Navigation("IdNotaDevolucionCompraNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasCreditosCompra", "IdNotaCreditoCompraNavigation")
                        .WithMany("NotasCreditosComprasDetalles")
                        .HasForeignKey("IdNotaCreditoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Compras_Detalles_Notas_Creditos_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("NotasCreditosComprasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Compras_Detalles_Productos");

                    b.Navigation("IdNotaCreditoCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosVenta", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasVenta", "IdFacturaVentaNavigation")
                        .WithMany("NotasCreditosVenta")
                        .HasForeignKey("IdFacturaVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Ventas_Facturas_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasDevolucionesVenta", "IdNotaDevolucionVentaNavigation")
                        .WithMany("NotasCreditosVenta")
                        .HasForeignKey("IdNotaDevolucionVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Ventas_Notas_Devoluciones_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Timbrado", "IdTimbradoNavigation")
                        .WithMany("NotasCreditosVenta")
                        .HasForeignKey("IdTimbrado")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Ventas_Timbrados");

                    b.Navigation("IdFacturaVentaNavigation");

                    b.Navigation("IdNotaDevolucionVentaNavigation");

                    b.Navigation("IdTimbradoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosVentasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasCreditosVenta", "IdNotaCreditoVentaNavigation")
                        .WithMany("NotasCreditosVentasDetalles")
                        .HasForeignKey("IdNotaCreditoVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Ventas_Detalles_Notas_Creditos_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("NotasCreditosVentasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Creditos_Ventas_Detalles_Productos");

                    b.Navigation("IdNotaCreditoVentaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasCompra", "IdFacturaCompraNavigation")
                        .WithMany("NotasDevolucionesCompras")
                        .HasForeignKey("IdFacturaCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Compras_Facturas_Compras");

                    b.Navigation("IdFacturaCompraNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasDevolucionesCompra", "IdNotaDevolucionCompraNavigation")
                        .WithMany("NotasDevolucionesComprasDetalles")
                        .HasForeignKey("IdNotaDevolucionCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Compras_Detalles_Notas_Devoluciones_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("NotasDevolucionesComprasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Compras_Detalles_Productos");

                    b.Navigation("IdNotaDevolucionCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesVenta", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasVenta", "IdFacturaVentaNavigation")
                        .WithMany("NotasDevolucionesVenta")
                        .HasForeignKey("IdFacturaVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Ventas_Facturas_Ventas");

                    b.Navigation("IdFacturaVentaNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesVentasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.NotasDevolucionesVenta", "IdNotaDevolucionVentaNavigation")
                        .WithMany("NotasDevolucionesVentasDetalles")
                        .HasForeignKey("IdNotaDevolucionVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Ventas_Detalles_Notas_Devoluciones_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("NotasDevolucionesVentasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Notas_Devoluciones_Ventas_Detalles_Productos");

                    b.Navigation("IdNotaDevolucionVentaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("OrdenesCompras")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Compras_Estados");

                    b.HasOne("DatabaseHastaCompraVenta.Models.PedidosCotizaciones", "IdPedidoCotizacionNavigation")
                        .WithMany("OrdenesCompras")
                        .HasForeignKey("IdPedidoCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Compras_Pedidos_Cotizaciones");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("OrdenesCompras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Compras_Proveedores");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdPedidoCotizacionNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesCompra", "IdOrdenCompraNavigation")
                        .WithMany("OrdenesComprasDetalles")
                        .HasForeignKey("IdOrdenCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Compras_Detalles_Ordenes_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("OrdenesComprasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Compras_Detalles_Productos");

                    b.Navigation("IdOrdenCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesMediosPagosCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.MediosPagosCompra", "IdMedioPagoCompraNavigation")
                        .WithMany("OrdenesMediosPagosCompras")
                        .HasForeignKey("IdMedioPagoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Medios_Pagos_Compras_Medios_Pagos_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesPagosCompra", "IdOrdenPagoCompraNavigation")
                        .WithMany("OrdenesMediosPagosCompras")
                        .HasForeignKey("IdOrdenPagoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Medios_Pagos_Compras_Ordenes_Pagos_Compras");

                    b.Navigation("IdMedioPagoCompraNavigation");

                    b.Navigation("IdOrdenPagoCompraNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesPagosCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("OrdenesPagosCompras")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Pagos_Compras_Estados");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("OrdenesPagosCompras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Pagos_Compras_Proveedores");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesPagosComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.FacturasCompra", "IdFacturaCompraNavigation")
                        .WithMany("OrdenesPagosComprasDetalles")
                        .HasForeignKey("IdFacturaCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Pagos_Compras_Detalles_Facturas_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesPagosCompra", "IdOrdenPagoCompraNavigation")
                        .WithMany("OrdenesPagosComprasDetalles")
                        .HasForeignKey("IdOrdenPagoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Pagos_Compras_Detalles_Ordenes_Pagos_Compras");

                    b.Navigation("IdFacturaCompraNavigation");

                    b.Navigation("IdOrdenPagoCompraNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesVenta", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Cliente", "IdClienteNavigation")
                        .WithMany("OrdenesVenta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Ventas_Clientes");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("OrdenesVenta")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Ventas_Estados");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Presupuesto", "IdPresupuestoNavigation")
                        .WithMany("OrdenesVenta")
                        .HasForeignKey("IdPresupuesto")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Ventas_Presupuestos");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdPresupuestoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesVentasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.OrdenesVenta", "IdOrdenVentaNavigation")
                        .WithMany("OrdenesVentasDetalles")
                        .HasForeignKey("IdOrdenVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Ventas_Detalles_Ordenes_Ventas");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("OrdenesVentasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Ventas_Detalles_Productos");

                    b.Navigation("IdOrdenVentaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Pariente", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Parientes")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Parientes_Empleados");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCompra", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("PedidosCompras")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Compras_Estados");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosComprasDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.PedidosCompra", "IdPedidoCompraNavigation")
                        .WithMany("PedidosComprasDetalles")
                        .HasForeignKey("IdPedidoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Compras_Detalles_Pedidos_Compras");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("PedidosComprasDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Compras_Detalles_Productos");

                    b.Navigation("IdPedidoCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCotizaciones", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("PedidosCotizaciones")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Cotizaciones_Estados");

                    b.HasOne("DatabaseHastaCompraVenta.Models.PedidosCompra", "IdPedidoCompraNavigation")
                        .WithMany("PedidosCotizaciones")
                        .HasForeignKey("IdPedidoCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Cotizaciones_Pedidos_Compras");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdPedidoCompraNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCotizacionesDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.PedidosCotizaciones", "IdPedidoCotizacionNavigation")
                        .WithMany("PedidosCotizacionesDetalles")
                        .HasForeignKey("IdPedidoCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Cotizaciones_Detalles_Pedidos_Cotizaciones");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("PedidosCotizacionesDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Cotizaciones_Detalles_Productos");

                    b.Navigation("IdPedidoCotizacionNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Persona", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("FK_Personas_Direcciones1");

                    b.Navigation("IdDireccionNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Presupuesto", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Presupuestos_Clientes");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Presupuestos_Estados");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PresupuestosDetalle", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Presupuesto", "IdPresupuestoNavigation")
                        .WithMany("PresupuestosDetalles")
                        .HasForeignKey("IdPresupuesto")
                        .IsRequired()
                        .HasConstraintName("FK_Presupuestos_Detalles_Presupuestos");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("PresupuestosDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Presupuestos_Detalles_Productos");

                    b.Navigation("IdPresupuestoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Producto", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categorias");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Marca", "IdMarcaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Marcas");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Proveedor", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Persona", "IdProveedorNavigation")
                        .WithOne("Proveedor")
                        .HasForeignKey("DatabaseHastaCompraVenta.Models.Proveedor", "IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Proveedores_Personas");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.StocksDeposito", b =>
                {
                    b.HasOne("DatabaseHastaCompraVenta.Models.Deposito", "IdDepositoNavigation")
                        .WithOne("StocksDeposito")
                        .HasForeignKey("DatabaseHastaCompraVenta.Models.StocksDeposito", "IdDeposito")
                        .IsRequired()
                        .HasConstraintName("FK_Stocks_Depositos_Depositos");

                    b.HasOne("DatabaseHastaCompraVenta.Models.Producto", "IdProductoNavigation")
                        .WithMany("StocksDepositos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Stocks_Depositos_Productos");

                    b.Navigation("IdDepositoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Ciudad", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Cliente", b =>
                {
                    b.Navigation("FacturasVenta");

                    b.Navigation("OrdenesVenta");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Deposito", b =>
                {
                    b.Navigation("StocksDeposito");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Direccion", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Empleado", b =>
                {
                    b.Navigation("Parientes");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Estado", b =>
                {
                    b.Navigation("OrdenesCompras");

                    b.Navigation("OrdenesPagosCompras");

                    b.Navigation("OrdenesVenta");

                    b.Navigation("PedidosCompras");

                    b.Navigation("PedidosCotizaciones");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasCompra", b =>
                {
                    b.Navigation("FacturasComprasDetalles");

                    b.Navigation("NotasCreditosCompras");

                    b.Navigation("NotasDevolucionesCompras");

                    b.Navigation("OrdenesPagosComprasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.FacturasVenta", b =>
                {
                    b.Navigation("FacturasVentasDetalles");

                    b.Navigation("NotasCreditosVenta");

                    b.Navigation("NotasDevolucionesVenta");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.MediosPagosCompra", b =>
                {
                    b.Navigation("FacturasVenta");

                    b.Navigation("OrdenesMediosPagosCompras");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosCompra", b =>
                {
                    b.Navigation("NotasCreditosComprasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasCreditosVenta", b =>
                {
                    b.Navigation("NotasCreditosVentasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesCompra", b =>
                {
                    b.Navigation("NotasCreditosCompras");

                    b.Navigation("NotasDevolucionesComprasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.NotasDevolucionesVenta", b =>
                {
                    b.Navigation("NotasCreditosVenta");

                    b.Navigation("NotasDevolucionesVentasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesCompra", b =>
                {
                    b.Navigation("FacturasCompras");

                    b.Navigation("OrdenesComprasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesPagosCompra", b =>
                {
                    b.Navigation("OrdenesMediosPagosCompras");

                    b.Navigation("OrdenesPagosComprasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.OrdenesVenta", b =>
                {
                    b.Navigation("FacturasVenta");

                    b.Navigation("OrdenesVentasDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCompra", b =>
                {
                    b.Navigation("PedidosComprasDetalles");

                    b.Navigation("PedidosCotizaciones");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.PedidosCotizaciones", b =>
                {
                    b.Navigation("OrdenesCompras");

                    b.Navigation("PedidosCotizacionesDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Persona", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Presupuesto", b =>
                {
                    b.Navigation("OrdenesVenta");

                    b.Navigation("PresupuestosDetalles");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Producto", b =>
                {
                    b.Navigation("FacturasComprasDetalles");

                    b.Navigation("FacturasVentasDetalles");

                    b.Navigation("NotasCreditosComprasDetalles");

                    b.Navigation("NotasCreditosVentasDetalles");

                    b.Navigation("NotasDevolucionesComprasDetalles");

                    b.Navigation("NotasDevolucionesVentasDetalles");

                    b.Navigation("OrdenesComprasDetalles");

                    b.Navigation("OrdenesVentasDetalles");

                    b.Navigation("PedidosComprasDetalles");

                    b.Navigation("PedidosCotizacionesDetalles");

                    b.Navigation("PresupuestosDetalles");

                    b.Navigation("StocksDepositos");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Proveedor", b =>
                {
                    b.Navigation("FacturasCompras");

                    b.Navigation("OrdenesCompras");

                    b.Navigation("OrdenesPagosCompras");
                });

            modelBuilder.Entity("DatabaseHastaCompraVenta.Models.Timbrado", b =>
                {
                    b.Navigation("FacturasVenta");

                    b.Navigation("NotasCreditosVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
