export const API_CONFIG = {
  BASE_URL:
    process.env.NEXT_PUBLIC_API_URL ??
    "https://sistemadegestion2026-production.up.railway.app",
  ENDPOINTS: {
    LOGIN: "/api/Auth/iniciar",
    PRODUCTS: "/api/Productos",
    CATEGORIES: "/api/Categorias",
    BRANDS: "/api/Marcas",
    PROVEEDORES: "/api/Proveedores",
    PAISES: "/api/Paises",
    CIUDADES: "/api/Ciudades",
    DIRECCIONES: "/api/Direcciones",
    CIUDADES_POR_PAIS: "/api/Ciudades/PorPais",
    PEDIDOS: "/api/PedidosCompras",
    PEDIDOS_DETALLES: "/api/PedidosComprasDetalles",
    STATUS: "/api/Estados",
    CLIENTS: "/api/Clientes",
    PRESUPUESTOS: "/api/Presupuestos",
    PRESUPUESTOS_DETALLES: "/api/PresupuestosDetalles",
    PRECIOS_VENTAS: "/api/PreciosVentas",
    COTIZACIONES: "/api/PedidosCotizaciones",
    COTIZACIONES_DETALLES: "/api/PedidosCotizacionesDetalles",
    PROCESOS_CONTABLES: "/api/ProcesosContables",
    EMPLEADOS: "/api/Empleados",
    PARIENTES: "/api/Parientes",
    PERIODOS_CONTABLES: "/api/PeriodosContables",
    CUENTAS_CONTABLES: "/api/CuentasContables",
    ASIENTOS: "/api/Asientos",
    ASIENTOS_COMPLETO: "/api/Asientos/completo",
    INVOICES: "/api/FacturasVentas",
    TIMBRADO: "/api/OrdenesVentas",
    BANCOS: "/api/Bancos",
    CUENTAS_BANCARIAS: "/api/CuentasBancarias",
    TIPOS_CUENTAS_BANCARIAS: "/api/TiposCuentasBancarias",
    MOVIMIENTOS_BANCARIOS: "/api/MovimientosBancarios",
    CHEQUES_EMITIDOS: "/api/ChequesEmitidos",
    DEPOSITOS_BANCARIOS: "/api/DepositosBancarios",
    TIPOS_DEPOSITOS_BANCARIOS: "/api/TiposDepositosBancarios",
    TIPOS_MOVIMIENTOS_BANCARIOS: "/api/TiposMovimientosBancarios",
    ORDENES_VENTAS: "/api/OrdenesVentas",
    MEDIOS_PAGO: "/api/MediosPagosCompras",
    STOCK: "/api/StocksDepositos",
    NOTAS_CREDITOS_VENTAS: "/api/NotasCreditosVentas",
  },
} as const;
