export const API_CONFIG = {
  BASE_URL: "https://sistemadegestion2026-production.up.railway.app",
  ENDPOINTS: {
    LOGIN: "/api/Auth/iniciar",
    PRODUCTS: "/api/Productos",
    CATEGORIES: "/api/Categorias",
    BRANDS: "/api/Marcas",
    PROVEEDORES: "/api/Proveedores",
    PAISES: "/api/Paises",
    CIUDADES: "/api/Ciudades",
    DIRECCIONES: "/api/Direcciones",
    CIUDADES_POR_PAIS: "/api/Ciudades/PorPais",
    PEDIDOS: "/api/PedidosCompras",
    PEDIDOS_DETALLES: "/api/PedidosComprasDetalles",
    STATUS: "/api/Estados",
    CLIENTS: "/api/Clientes",
    PRESUPUESTOS: "/api/Presupuestos",
    PRESUPUESTOS_DETALLES: "/api/PresupuestosDetalles",
    PRECIOS_VENTAS: "/api/PreciosVentas",
    COTIZACIONES: "/api/PedidosCotizaciones",
    COTIZACIONES_DETALLES: "/api/PedidosCotizacionesDetalles",
  },
} as const;
