export const API_CONFIG = {
  BASE_URL: "https://sistemadegestion2026-production.up.railway.app",
  ENDPOINTS: {
    LOGIN: "/api/Auth/iniciar",
    PRODUCTS: "/api/Productos",
    CATEGORIES: "/api/Categorias",
    BRANDS: "/api/Marcas",
    PROVEEDORES: "/api/Proveedores",
    PAISES: "/api/Paises",
    CIUDADES: "/api/Ciudades",
    DIRECCIONES: "/api/Direcciones",
    CIUDADES_POR_PAIS: "/api/Ciudades/PorPais",
    PEDIDOS: "/api/PedidosCompras",
    PEDIDOS_DETALLES: "/api/PedidosComprasDetalles",
    COTIZACIONES: "/api/PedidosCotizaciones",
    COTIZACIONES_DETALLES: "/api/PedidosCotizacionesDetalles",
    ORDENES_COMPRA: "/api/OrdenesCompras",
    ORDENES_COMPRA_DETALLES: "/api/OrdenesComprasDetalles",
    FACTURAS_COMPRA: "/api/FacturasCompras",
    FACTURAS_COMPRA_DETALLES: "/api/FacturasComprasDetalles",
    ORDENES_PAGO_COMPRA: "/api/OrdenesPagosCompras",
    ORDENES_PAGO_COMPRA_DETALLES: "/api/OrdenesPagosComprasDetalles",
    NOTAS_CREDITO_COMPRA: "/api/NotasCreditosCompras",
    NOTAS_CREDITO_COMPRA_DETALLES: "/api/NotasCreditosComprasDetalles",
    MEDIOS_PAGO_COMPRA: "/api/MediosPagoCompras",
    CUENTAS_BANCARIAS: "/api/CuentasBancarias",
    MOVIMIENTOS_BANCARIOS: "/api/MovimientosBancarios",
    BANCOS: "/api/Bancos",
    CUENTAS_CONTABLES: "/api/CuentasContables",
  },
} as const;
